# Database server docker-compose
# Deploy this on your central database server

version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: soulseek
      POSTGRES_USER: soulseek
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme123}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data: